# Generated by Django 4.2.24 on 2025-10-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_category_recipe_meal_type_and_more'),
        ('mealplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealslot',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealslot',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mealslot',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Elevenses', 'Elevenses'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mealslot',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_slots', to='recipes.recipe'),
        ),
    ]
