# Generated by Django 4.2.24 on 2025-10-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes",
         "0005_rename_user_notification_recipient_notification_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cook_time",
            field=models.IntegerField(
                help_text="Cooking time in minutes"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("snacks", "Snacks & Appetizers"),
                    ("dessert", "Desserts"),
                    ("beverages", "Beverages"),
                ],
                default="dinner",
                help_text="Select the meal type for this recipe",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="prep_time",
            field=models.IntegerField(help_text="Preparation time in minutes"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
